config/routes.rb
Rails.application.routes.draw do
  resources :static_pages
  get 'pricing' => 'static_pages#pricing'
  get 'search' => 'contacts#search'
  resources :contacts
  get "content/silver"
  get "content/gold"
  get "content/platinum"
  mount Payola::Engine => '/payola', as: :payola
  mount Upmin::Engine => '/admin'
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # root to: "devise/sessions#new"
  get 'products/:id', to: 'products#show', :as => :products
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'change_plan', :to => 'registrations#change_plan'
  end
  resources :lists do
    resources :contacts, only: :index, controller: 'list_contacts'
  end

  resources :contacts, only: [], controller: 'list_contacts' do
    post 'add_to_list', on: :collection
  end
  resources :users
  resources :listings

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get 'pages/blog' => 'high_voltage/pages#show', id: 'blog'
  get 'pages/contact' => 'high_voltage/pages#show', id: 'contact'
  get 'pages/faqs' => 'high_voltage/pages#show', id: 'faqs'
  get 'pages/features' => 'high_voltage/pages#show', id: 'features'
  get 'pages/for-agencies' => 'high_voltage/pages#show', id: 'for-agencies'
  get 'pages/for-charities' => 'high_voltage/pages#show', id: 'for-charities'
  get 'pages/for-freelancers' => 'high_voltage/pages#show', id: 'for-freelanceers'
  get 'pages/for-startups' => 'high_voltage/pages#show', id: 'for-startups'
  get 'pages/help' => 'high_voltage/pages#show', id: 'help'
  get 'pages/privacy' => 'high_voltage/pages#show', id: 'privacy'
  get 'pages/terms' => 'high_voltage/pages#show', id: 'terms'
  get '/blog', to: 'blog#redirect'
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :listings
  has_many :contacts, through: :listings

  belongs_to :owner, :class_name => 'User'
  has_and_belongs_to_many :contacts, before_add: :check_exist?

  private

  def check_exist?(contact)
    raise ActiveRecord::Rollback if contacts.include? contact
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :search

  
  expose(:lists)
  expose(:list, attributes: :list_params)
  expose(:contacts, ancestor: :list)

  # GET /lists
  # GET /lists.json
  def index
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    respond_to do |format|
      if list.save
        format.html { redirect_to list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: list }
      else
        format.html { render :new }
        format.json { render json: list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if list.update(list_params)
        format.html { redirect_to list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: list }
      else
        format.html { render :edit }
        format.json { render json: list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def list_params
    params.require(:list).permit(:name)
  end
  
  def search
    if params[:search]
      search_params = CGI::escapeHTML(params[:search]) 
      redirect_to ("/contacts?utf8=%E2%9C%93&search=#{search_params}")
    end
  end  
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<br>

<%= link_to 'Create New List', new_list_path, class: "btn btn-success"  %>

<br>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>List Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% lists.each do |list| %>
      <tr>
        <td><h3><%= list.name %></h3></td>
        <td><%= link_to 'View List ', list_path(list), class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit List Name', edit_list_path(list), class: "btn btn-warning" %></td>
        <td><%= link_to 'Delete List', list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<br>
<br>

<h1><%= list.name %> list</h1>

<%= link_to "Download List", list_contacts_path(list, format: :csv), class: "btn btn-success" %>
<%= link_to 'Edit List Name', edit_list_path(list), class: "btn btn-primary" %>
<%= link_to 'View All Lists', lists_path, class: "btn btn-warning" %>
<%= link_to 'New List', new_list_path, class: "btn btn-danger"  %>

<br>
<br>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last name</th>
      <th>Title</th>
      <th>Publication</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Twitter</th>
      <th>Lists</th>
    </tr>
  </thead>
  <tbody>
    <% contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.title %></td>
        <td><%= contact.publication %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.twitter %></td>
        <td>
          <div class='btn-group dropdown'>
            <button type='button' style='width:100%;' class='btn btn-primary dropdown-toggle'><span class='fa fa-gear'></span> Remove From List </button>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>