config/routes.rb
Rails.application.routes.draw do
  resources :static_pages
  get 'pricing' => 'static_pages#pricing'
  get 'search' => 'contacts#search'
  resources :contacts
  get "content/silver"
  get "content/gold"
  get "content/platinum"
  mount Payola::Engine => '/payola', as: :payola
  mount Upmin::Engine => '/admin'
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # root to: "devise/sessions#new"
  get 'products/:id', to: 'products#show', :as => :products
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'change_plan', :to => 'registrations#change_plan'
  end
  resources :lists do
    resources :contacts, only: :index, controller: 'list_contacts'
  end

  resources :contacts, only: [], controller: 'list_contacts' do
    post 'add_to_list', on: :collection
  end
  resources :users
  resources :listings

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get 'pages/blog' => 'high_voltage/pages#show', id: 'blog'
  get 'pages/contact' => 'high_voltage/pages#show', id: 'contact'
  get 'pages/faqs' => 'high_voltage/pages#show', id: 'faqs'
  get 'pages/features' => 'high_voltage/pages#show', id: 'features'
  get 'pages/for-agencies' => 'high_voltage/pages#show', id: 'for-agencies'
  get 'pages/for-charities' => 'high_voltage/pages#show', id: 'for-charities'
  get 'pages/for-freelancers' => 'high_voltage/pages#show', id: 'for-freelanceers'
  get 'pages/for-startups' => 'high_voltage/pages#show', id: 'for-startups'
  get 'pages/help' => 'high_voltage/pages#show', id: 'help'
  get 'pages/privacy' => 'high_voltage/pages#show', id: 'privacy'
  get 'pages/terms' => 'high_voltage/pages#show', id: 'terms'
  get '/blog', to: 'blog#redirect'
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: 'Static page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params.require(:static_page).permit(:home, :help, :faqs, :contact, :terms, :privacy, :about, :pricing)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home %><br>
    <%= f.text_field :home %>
  </div>
  <div class="field">
    <%= f.label :help %><br>
    <%= f.text_field :help %>
  </div>
  <div class="field">
    <%= f.label :faqs %><br>
    <%= f.text_field :faqs %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :terms %><br>
    <%= f.text_field :terms %>
  </div>
  <div class="field">
    <%= f.label :privacy %><br>
    <%= f.text_field :privacy %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :pricing %><br>
    <%= f.text_field :pricing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Static Pages</h1>

<table>
  <thead>
    <tr>
      <th>Home</th>
      <th>Help</th>
      <th>Faqs</th>
      <th>Contact</th>
      <th>Terms</th>
      <th>Privacy</th>
      <th>About</th>
      <th>Pricing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= static_page.home %></td>
        <td><%= static_page.help %></td>
        <td><%= static_page.faqs %></td>
        <td><%= static_page.contact %></td>
        <td><%= static_page.terms %></td>
        <td><%= static_page.privacy %></td>
        <td><%= static_page.about %></td>
        <td><%= static_page.pricing %></td>
        <td><%= link_to 'Show', static_page %></td>
        <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
        <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/pricing.html.erb
<div class="row col-sm-12 plans">
    <div class="col-sm-2 well">
      <div class="plan"><h2>Silver</h2></div>
      <a class="list-unstyled">
        <li>One lesson a month</li>
      </ul>
      <h3>$9/month</h3>
      <%= link_to 'Subscribe', new_user_registration_path(plan: 'silver'), :class => 'btn btn-primary' %>
    </div>
    <div class="col-sm-2 well featured">
      <div class="plan featured-plan"><h2>Gold</h2></div>
      <ul class="list-unstyled">
        <li>Ten lessons a month</li>
      </ul>
      <h3>$19/month</h3>
      <%= link_to 'Subscribe', new_user_registration_path(plan: 'gold'), :class => 'btn btn-primary' %>
    </div>
    <div class="col-sm-2 well">
      <div class="plan"><h2>Platinum</h2></div>
      <ul class="list-unstyled">
        <li>Thirty lessons a month</li>
      </ul>
      <h3>$29/month</h3>
      <%= link_to 'Subscribe', new_user_registration_path(plan: 'platinum'), :class => 'btn btn-primary' %>
    </div>
  </div>

app/views/static_pages/search.html.erb
<h1>Find Contacts</h1>
<%= search_form_for @search, url: contacts_path do |f| %>
<%= f.search_field :first_name_or_last_name_or_title_or_publication_cont, placeholder: 'Search by name, title or publication', class: 'form-control' %><%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>
<br>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home:</strong>
  <%= @static_page.home %>
</p>

<p>
  <strong>Help:</strong>
  <%= @static_page.help %>
</p>

<p>
  <strong>Faqs:</strong>
  <%= @static_page.faqs %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @static_page.contact %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @static_page.terms %>
</p>

<p>
  <strong>Privacy:</strong>
  <%= @static_page.privacy %>
</p>

<p>
  <strong>About:</strong>
  <%= @static_page.about %>
</p>

<p>
  <strong>Pricing:</strong>
  <%= @static_page.pricing %>
</p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>