config/routes.rb
Rails.application.routes.draw do
  resources :static_pages
  get 'pricing' => 'static_pages#pricing'
  get 'search' => 'contacts#search'
  resources :contacts
  get "content/silver"
  get "content/gold"
  get "content/platinum"
  mount Payola::Engine => '/payola', as: :payola
  mount Upmin::Engine => '/admin'
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # root to: "devise/sessions#new"
  get 'products/:id', to: 'products#show', :as => :products
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'change_plan', :to => 'registrations#change_plan'
  end
  resources :lists do
    resources :contacts, only: :index, controller: 'list_contacts'
  end

  resources :contacts, only: [], controller: 'list_contacts' do
    post 'add_to_list', on: :collection
  end
  resources :users
  resources :listings

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get 'pages/blog' => 'high_voltage/pages#show', id: 'blog'
  get 'pages/contact' => 'high_voltage/pages#show', id: 'contact'
  get 'pages/faqs' => 'high_voltage/pages#show', id: 'faqs'
  get 'pages/features' => 'high_voltage/pages#show', id: 'features'
  get 'pages/for-agencies' => 'high_voltage/pages#show', id: 'for-agencies'
  get 'pages/for-charities' => 'high_voltage/pages#show', id: 'for-charities'
  get 'pages/for-freelancers' => 'high_voltage/pages#show', id: 'for-freelanceers'
  get 'pages/for-startups' => 'high_voltage/pages#show', id: 'for-startups'
  get 'pages/help' => 'high_voltage/pages#show', id: 'help'
  get 'pages/privacy' => 'high_voltage/pages#show', id: 'privacy'
  get 'pages/terms' => 'high_voltage/pages#show', id: 'terms'
  get '/blog', to: 'blog#redirect'
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/views/visitors/index.html.erb
<%= content_for :page_title, 'Media Database - Find journalists contacts easily with our media database tool' %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h3>Admin</h3>
    <p><%= link_to 'User count:', users_path %> <%= User.count %></p>
    <h3>You've signed up. Download a free book.</h3>
    <%= link_to 'Download PDF', products_path('product.pdf'), class: 'btn btn-success btn-large' %>
  <% end %>
<div class="container">
        <div class="row" align="center">
          <div class="col-lg-3">
          </div>
          <div class="col-lg-6">
            &nbsp;
            &nbsp;
            <h3>Search xx contacts from xx publications</h3>
            </br>
            <div>
              <%= form_tag(contacts_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search contacts" %>
                <%= submit_tag "Search" %>
              <% end %>
            </div>
          </div>
            <div class="col-lg-3">
            </div>
        </div>
     </div>
<% else %>
  <div class="container">
    <div class="row" align="center">
      &nbsp;
      <h1>Find media contacts <b>easily<b><h1>
      <h3>Media Database is the simple media contacts tool.</h3>
    </div>
        &nbsp;
    <div class="row">
      <p align="center"><%= link_to "Start Your Free Trial", pricing_path, :class => "btn btn-lg btn-danger" %></p>
      <p align="center" class="small"><i>No Downloads. No Hassle.</i></p>
    </div>
  </div>
        &nbsp;
        <div class="row">
          <h4 align="center">Search over 10,000 journalists, bloggers and influencers from thousands of publications.</h4>
            </br>
            <div align="center">
              <%= form_tag(contacts_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search contacts" %>
                <%= submit_tag "Search" %>
              <% end %>
            </div>
        </div>
          
     <div class="row">
      <p><img src="http://www.emplify.io/static/images/design/emplify-design-over-time.png"></p>
    </div>
&nbsp;
      <div class="row">
      <p>&nbsp;</p>
        <strong><h2 align="center"><b>Less Time Searching, More Time Connecting with Journalists</b></h2></strong>
      <p>&nbsp;</p>
        <h4 align="center">Media Database helps Startups, Freelancers and Small Businesses tell their story to journalists, bloggers and influencers around the world.</h4>
        <p>&nbsp;</p>
        <h5>Media Database lets you:</h5>
        <p><b>Save time!</b>You can find the journalists, bloggers and other media contacts for your entire PR campaign in just a few minutes. Building media contacts manually takes hours -- hours that you could better spend doing what you do best: telling them about your brilliant business.
        </p>
        <p><b>Save money!</b> Don't spend hundreds on buying single contact lists from traditional media databases -- Media Database can make an infinite number of lists for you! If you plan on contacting journalists three times or more in your business' lifetime it's much cheaper to build your own media list!
        </p>
        <p>
          <b>Save contacts!</b> With Media Database, you can build multiple contacts lists for your different projects or different media types, then either save them online or export them to Excel for later use.
        </p>
        <p>
  Tailor your media lists! If you buy media lists from database providers, you're limited to what contacts they have found.  If you add your media contacts yourself, you will always be able to match them directly to your other media contacts.  Try adding your own jouranalists or blogger contact details, for example.
        </p>
        <p>
  Find journalists and bloggers writing about almost any subject! If you can type it on your computer, you can put it on a media list. Media lists, letters, numbers, math facts, social studies facts, student names great for first day jitters), famous people -- the choices are endless! See some examples of what we've done with this flexibility.
        </p>
  Never buy another media database! We at Media Database understand that budgets are tight. Accordingly, we will never charge you for an upgrade to the software. In addition, unlike some media database companies our software can be used year after year without requiring additional license fees. Media Database is very affordable on any budget.
        </p>
        <p>  
  Buy with confidence. In addition to a free trial so you can see if Media Database is exactly right foryou, we offer an unconditional 30 day money-back guarantee. If you'renot absolutely thrilled with our software, we don't deserve your money.
        </p>
        <p>  
  Don't believe us? Over 328,000 people have used Media Database:
  "Thanks again ... I would highly recommend it to anyone I talk to!!!" – Glenda D.
  Media Datavase works for Windows PCs and Macs. You can use it both at your home and school, and it saves your media contacts in one place.</p>
        <%= link_to "Try Now!", "/users/sign_up", :class => "btn btn-primary" %>
  <p>
  15 seconds to get started.
  </p>
  <h3>Want To Try It Yourself?</h3>
  <p>You can make media lists like those. Try Media Database for free to see how easy it is to use. You'll be done in 15 seconds.</p>
        <%= link_to "Try Now!", "/users/sign_up", :class => "btn btn-primary" %>
  <p>15 seconds to get started.</p>

      <p align="center"> ©2001-2014 All Rights Reserved. MediaDatabase® is a registered trademark of Montfort Consultancy Ltd. Privacy and Terms</p>
<% end %>