config/routes.rb
Rails.application.routes.draw do
  resources :static_pages
  get 'pricing' => 'static_pages#pricing'
  get 'search' => 'contacts#search'
  resources :contacts
  get "content/silver"
  get "content/gold"
  get "content/platinum"
  mount Payola::Engine => '/payola', as: :payola
  mount Upmin::Engine => '/admin'
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # root to: "devise/sessions#new"
  get 'products/:id', to: 'products#show', :as => :products
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'change_plan', :to => 'registrations#change_plan'
  end
  resources :lists do
    resources :contacts, only: :index, controller: 'list_contacts'
  end

  resources :contacts, only: [], controller: 'list_contacts' do
    post 'add_to_list', on: :collection
  end
  resources :users
  resources :listings

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get 'pages/blog' => 'high_voltage/pages#show', id: 'blog'
  get 'pages/contact' => 'high_voltage/pages#show', id: 'contact'
  get 'pages/faqs' => 'high_voltage/pages#show', id: 'faqs'
  get 'pages/features' => 'high_voltage/pages#show', id: 'features'
  get 'pages/for-agencies' => 'high_voltage/pages#show', id: 'for-agencies'
  get 'pages/for-charities' => 'high_voltage/pages#show', id: 'for-charities'
  get 'pages/for-freelancers' => 'high_voltage/pages#show', id: 'for-freelanceers'
  get 'pages/for-startups' => 'high_voltage/pages#show', id: 'for-startups'
  get 'pages/help' => 'high_voltage/pages#show', id: 'help'
  get 'pages/privacy' => 'high_voltage/pages#show', id: 'privacy'
  get 'pages/terms' => 'high_voltage/pages#show', id: 'terms'
  get '/blog', to: 'blog#redirect'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :listings
  has_many :lists, through: :listings

  belongs_to :owner, :class_name => 'User'
  belongs_to :user
  has_and_belongs_to_many :lists, before_add: :check_exist?

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      find_each do |contact|
        csv << contact.attributes.values_at(*column_names)
      end
    end
  end

  private

  def check_exist?(list)
    raise ActiveRecord::Rollback if lists.include? list
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :listings
  has_many :contacts, through: :listings

  belongs_to :owner, :class_name => 'User'
  has_and_belongs_to_many :contacts, before_add: :check_exist?

  private

  def check_exist?(contact)
    raise ActiveRecord::Rollback if contacts.include? contact
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @lists = List.all
    @search = Contact.search(params[:q])
    @contacts = @search.result(distinct: true).paginate(page: params[:page], per_page: 25)
  end
  
  def search
    @lists = List.all
    @search = Contact.search(params[:q])
    @contacts = @search.result(distinct: true).paginate(page: params[:page], per_page: 25)
    render template: 'contacts/index'
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.includes(:lists).find(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @lists = List.all
  end

  # GET /contacts/1/edit
  def edit
    @lists = List.all
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @lists = List.all

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :title, :publication, :email, :twitter, :verified)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def list_links(lists)
    links = lists.collect{|list| link_to lists.name, lists_path(list)}
    return links.join(", ").html_safe
  end
  
  def index
    @q = Contact.ransack(params[:q])
    @contacts = @q.result(distinct: true)
  end
  
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publication %><br>
    <%= f.text_field :publication %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :verified %><br>
    <%= f.check_box :verified %>
  </div>
  <div class="field">
    <%= f.label :list %><br>
    <%= f.collection_select :lists, @lists, :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/_listings_form.html.erb
<h1>Select list to add contact to:</h1>

<%= form_tag listings_path do %>
  <%= hidden_field_tag :contact_id, @contact.id %>
  <%= select_tag :list_id, options_from_collection_for_select(List.all, :id, :name), class: "form-control input-lg"  %></br>
  <%= submit_tag "Add to List", class: "btn btn-primary" %>
<% end %> 

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="row">
  <%= search_form_for @search do |f| %>
  <h1>Search Contacts:</h1> 
    <%= f.search_field :first_name_or_last_name_or_title_or_publication_cont, placeholder: 'Search by name, title or publication', class: 'form-control input-group' %>
      <%= f.submit nil, :class => 'btn btn-default' %>
  <% end %>
</div>
<br>
<%= form_tag add_to_list_contacts_path, method: :post do %>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= check_box_tag 'select-all' %></th>
      <th><%= sort_link(@search, :first_name, "First Name") %></th>
      <th><%= sort_link(@search, :last_name, "Last Name") %></th>
      <th><%= sort_link(@search, :title, "Title") %></th>
      <th><%= sort_link(@search, :name, "Publication") %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= check_box_tag 'contact_ids[]', contact.id, false, class: 'contact-checkbox' %></td>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.title %></td>
        <td><%= contact.publication %></td>
        <td><%= link_to 'View Contact', contact, class: "btn btn-primary" %></td>
        <td><%= link_to 'Add To List', contact, class: "btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<h4>Add selected contacts to list:</h4>
<%= select_tag 'list_id', options_from_collection_for_select(@lists, :id, :name), class: 'form-control' %>
<%= submit_tag 'Add Contacts', :class => 'btn btn-primary' %>
<% end %>
<%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
<br>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
	<div class="row">
    </br>
                    <h3>Say hello to</h3>
                    <h2><%= @contact.first_name %> <%= @contact.last_name %></h2>
                    <h4><%= @contact.title %>, <%= @contact.publication %></h4>
                    <p>
                      <strong>Phone:</strong>
                      <%= @contact.phone %>
                    </p>              
                    <p>
                      <strong>Email:</strong>
                      <%= @contact.email %>
                    </p>

                    <p>
                      <strong>Twitter:</strong>
                      <%= @contact.twitter %>
                    </p>
                </div>
</div>

<%= render "listings_form" %></br>

<%= link_to 'New List', new_list_path, class: "btn btn-danger" %></br>

<% if current_user.admin? %>
  <%= link_to 'Edit', edit_contact_path(@contact) %> |
  <%= link_to 'Back', contacts_path %>
<% else %>
<% end %>
<div class="container">
	<div class="row">
                    <h2><%= @contact.first_name %> <%= @contact.last_name %></h2>
                    <h4><%= @contact.title %>, <%= @contact.publication %></h4>
                    <p>
                      <strong>Phone:</strong>
                      <a href="/">Sign in to view</a>
                    </p>              
                    <p>
                      <strong>Email:</strong>
                      <a href="/">Sign in to view</a>
                    </p>

                    <p>
                      <strong>Twitter:</strong>
                      <%= @contact.twitter %>
                    </p>
                </div>
</div>